### ISSUE TITLE
render exception using an injected viewmodel

### ISSUE THREAD

**Issue by MatthiasFsd** [FlorianRappl/Piral.Blazor#125]
# Bug Report

## Environment Details and Version

latest Version from blazor-7.0 branch
Piral-Blazor: 7.0.9-pre.20230828.1
OS: Windows 10
Browser: Edge, Firefox

## Description

A viewmodel registered as scoped in modules.cs
`services.AddScoped<IViewModel, ViewModel>();`

It is injected in counter.razor and text1.razor

The constructor of the viewmodel is call twice even if it is used in the same scope only. This probably causes a render exception and the counter page is not updated.
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The render handle is not yet assigned.
System.InvalidOperationException: The render handle is not yet assigned.
   at Microsoft.AspNetCore.Components.RenderHandle.ThrowNotInitialized()
   at Microsoft.AspNetCore.Components.RenderHandle.get_Dispatcher()
   at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
   at ViewModelInjectComponentBase`1[[IViewModel, Pilet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnPropertyChanged(Object sender, PropertyChangedEventArgs e) in C:\temp\sample\RenderException\ViewModelInjectComponentBase{T}.cs:line 42
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(PropertyChangedEventArgs e)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(String propertyName)
   at ViewModel.OnSaveSampleChanged(Object sender, PropertyChangedEventArgs e) in C:\temp\sample\RenderException\ViewModel.cs:line 21
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(PropertyChangedEventArgs e)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(String propertyName)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.SetProperty[Int32](Int32& field, Int32 newValue, String propertyName)
   at SaveSample.set_CurrentCount(Int32 value) in C:\temp\sample\RenderException\SaveSample.cs:line 8
   at ViewModel.set_CurrentCount(Int32 value) in C:\temp\sample\RenderException\ViewModel.cs:line 24
   at Pilet.Components.CounterPage.IncrementCount() in C:\temp\sample\RenderException\Components\CounterPage.razor:line 21
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```

## Steps to Reproduce

Build the provided sample based on the standalone example from blazor-7.0 branch.
Start and load the counter page
Press the Increment Button

## Expected behavior

No render exception
Both views of the example use the same instance of the injected viewmodel because they share the same scope. The constructor of the viewmodel is only called once.

## Actual behavior

The views use diverent viewmodels.
Render exception is thrown.

[RenderException.zip](https://github.com/smapiot/Piral.Blazor/files/12497324/RenderException.zip)

**Comment by FlorianRappl** [comment]
Thanks for the repro - I will investigate this!

**Comment by FlorianRappl** [comment]
This is fixed in the latest preview and will be part of the v9.
