### ISSUE TITLE
piral-adal not working with blazor from app-shell

### ISSUE THREAD

**Issue by anders130** [FlorianRappl/Piral.Blazor#128]
# Bug Report

## Environment Details and Version

- Piral Version: 1.3.3
- Blazor Verion: net7.0.10 / 7.0.11
- OS: Windows 11
- Browser: Firefox, Edge, Chrome
- Node Version: v20.7.0
- Piral.Blazor: 7.0.10-pre.20231110.1

## Description

I created an app-shell with the piral-adal authentication. Inside a blazor pilet I am using the PiletService to retrieve the token and use it as part of a custom AuthenticationProvider. When I debug the pilet, it works. But when I try to use it by loading it from the feed service by debugging the app-shell, the following error occurs:

```txt
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Components.Authorization.AuthorizeDataAdapter[]' from assembly ''.
   at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Piral.Blazor.Core.PiletComponentActivator.CreateInstance(Type componentType)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

## Steps to Reproduce

1. clone my repo on auth branch (https://github.com/anders130/piral-distributed-example/tree/auth)
2. run the app-shell
or
1. build the pilets and publish to your own feed-service
2. edit the feed-service url in the app-shell and start the app-shell

## Expected Behavior

It has to work exactly like it does, when debugging the pilets from visual studio.

## Actual behavior

The blazor pilets simply don't render at all.

**Comment by FlorianRappl** [comment]
Unfortunately, the MWE is not really working (config file missing, had to delete the npmrc etc.). With the configuration that I used it seems to work just well (provided deployment of my own pilet - the problem is definitely inside the deployed pilets, which I did not use / change).

From my perspective it looks such that additional trimming was applied and that the relevant code is trimmed away. I'd recommend to modify / play around with the trimming settings.

**Comment by anders130** [comment]
It appears that my AppRoot Component isn't getting published, whereas everything else is. How and where can I change the trimming settings to avoid that behavior?

**Comment by FlorianRappl** [comment]
The property group of the project -> `<PublishTrimmed>false</PublishTrimmed>`

If its really only about that one component you could "mention it" in the Module file - to trick the trimmer.

**Comment by anders130** [comment]
I have added `<PublishTrimmed>false</PublishTrimmed>` to the property group inside the csproj file and I have also tried to "mention the approot" in the Module.cs:
```cs
    public static void ConfigureServices(IServiceCollection services)
    {
        var root = new AppRoot();
        services.AddOptions();
        services.AddAuthorizationCore();
        services.AddScoped<AuthenticationStateProvider, CustomAuthProvider>();
    }
```

It unfortunately didn't fix the problem. The AppRoot is still missing in the published pilet.

**Comment by FlorianRappl** [comment]
Are you sure the AppRoot is missing? I've downloaded the dll from the BlazorPilet.Counter and there it seems to be present.

**Comment by anders130** [comment]
Yes, I am relatively sure. I have added the following AppRoot.razor to the BlazorPilet.Counter2 Project:
```csharp
@attribute [PiralAppRoot]

<div style="color: green">
    @ChildContent
</div>

@code {
    [Parameter]
    public RenderFragment ChildContent { get; set; } = null!;
}
```
When I debug it, All components of that project have green text. When I now publish that new version of the pilet and run the app-shell with only that pilet (for safety), the components are not green.
Debug picture (http://localhost:5155/counter2):
![grafik](https://github.com/smapiot/Piral.Blazor/assets/93037023/78d980a6-b678-4843-8ddf-590c049e053d)
app-shell after publish (http://localhost:1234/counter2):
![grafik](https://github.com/smapiot/Piral.Blazor/assets/93037023/c11f999f-77d5-4f69-bb21-cb4f64f332bf)

**Comment by anders130** [comment]
A little update on this issue:
The missing green color was just a browser caching error. By deleting all browser data, I was able to see the green color again.
Unfortunately this does not solve the error I am having with the `CascadingAuthenticationState`. 

The error still appears, when I use a static token instead of the accessToken I get from the PiletService. Also I reverted the app-shell back to a state without any authentication (aka the state of the app-shell in the dev branch), while still using the string for the token (I will not share the token due to privacy issues).
```txt
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Components.Authorization.AuthorizeDataAdapter[]' from assembly ''.
   at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Piral.Blazor.Core.PiletComponentActivator.CreateInstance(Type componentType)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
To conclude, a blazor pilet throws that error whenever a `CascadingAuthenticationState` is inside the AppRoot.
I hope this helps.

**Comment by FlorianRappl** [comment]
Yeah so this is definitely something with the trimmer and an issue that only appears when publishing from VS. Anyway, we have this cracked and in v10 it should work without a problem.
